INSERT INTO CAMPUSES VALUES (0,'Arizona State University','Massachusetts Institute of Technology (MIT)',2636);
INSERT INTO CAMPUSES VALUES (1,'Arizona State University','Northwestern',1756);
INSERT INTO CAMPUSES VALUES (2,'Arizona State University','Ohio State University',1865);
INSERT INTO CAMPUSES VALUES (3,'Arizona State University','Saddleback College',379);
INSERT INTO CAMPUSES VALUES (4,'Arizona State University','University of  Michigan',1956);
INSERT INTO CAMPUSES VALUES (5,'Arizona State University','University of California, Irvine (UCI)',375);
INSERT INTO CAMPUSES VALUES (6,'Arizona State University','University of California, Los Angeles (UCLA)',397);
INSERT INTO CAMPUSES VALUES (7,'Arizona State University','University of Oregon',1343);
INSERT INTO CAMPUSES VALUES (8,'Arizona State University','University of the Pacific',720);
INSERT INTO CAMPUSES VALUES (9,'Arizona State University','University of Wisconsin',1684);
INSERT INTO CAMPUSES VALUES (10,'Massachusetts Institute of Technology (MIT)','Arizona State University',2636);
INSERT INTO CAMPUSES VALUES (11,'Massachusetts Institute of Technology (MIT)','Northwestern',993);
INSERT INTO CAMPUSES VALUES (12,'Massachusetts Institute of Technology (MIT)','Ohio State University',772);
INSERT INTO CAMPUSES VALUES (13,'Massachusetts Institute of Technology (MIT)','Saddleback College',2989);
INSERT INTO CAMPUSES VALUES (14,'Massachusetts Institute of Technology (MIT)','University of  Michigan',803);
INSERT INTO CAMPUSES VALUES (15,'Massachusetts Institute of Technology (MIT)','University of California, Irvine (UCI)',2986);
INSERT INTO CAMPUSES VALUES (16,'Massachusetts Institute of Technology (MIT)','University of California, Los Angeles (UCLA)',2998);
INSERT INTO CAMPUSES VALUES (17,'Massachusetts Institute of Technology (MIT)','University of Oregon',3107);
INSERT INTO CAMPUSES VALUES (18,'Massachusetts Institute of Technology (MIT)','University of the Pacific',3057);
INSERT INTO CAMPUSES VALUES (19,'Massachusetts Institute of Technology (MIT)','University of Wisconsin',1125);
INSERT INTO CAMPUSES VALUES (20,'Northwestern','Arizona State University',1756);
INSERT INTO CAMPUSES VALUES (21,'Northwestern','Massachusetts Institute of Technology (MIT)',993);
INSERT INTO CAMPUSES VALUES (22,'Northwestern','Ohio State University',335);
INSERT INTO CAMPUSES VALUES (23,'Northwestern','Saddleback College',2033);
INSERT INTO CAMPUSES VALUES (24,'Northwestern','University of  Michigan',270);
INSERT INTO CAMPUSES VALUES (25,'Northwestern','University of California, Irvine (UCI)',2030);
INSERT INTO CAMPUSES VALUES (26,'Northwestern','University of California, Los Angeles (UCLA)',2043);
INSERT INTO CAMPUSES VALUES (27,'Northwestern','University of Oregon',2151);
INSERT INTO CAMPUSES VALUES (28,'Northwestern','University of the Pacific',2102);
INSERT INTO CAMPUSES VALUES (29,'Northwestern','University of Wisconsin',145);
INSERT INTO CAMPUSES VALUES (30,'Ohio State University','Arizona State University',1865);
INSERT INTO CAMPUSES VALUES (31,'Ohio State University','Massachusetts Institute of Technology (MIT)',772);
INSERT INTO CAMPUSES VALUES (32,'Ohio State University','Northwestern',335);
INSERT INTO CAMPUSES VALUES (33,'Ohio State University','Saddleback College',2252);
INSERT INTO CAMPUSES VALUES (34,'Ohio State University','University of  Michigan',184);
INSERT INTO CAMPUSES VALUES (35,'Ohio State University','University of California, Irvine (UCI)',2248);
INSERT INTO CAMPUSES VALUES (36,'Ohio State University','University of California, Los Angeles (UCLA)',2261);
INSERT INTO CAMPUSES VALUES (37,'Ohio State University','University of Oregon',2241);
INSERT INTO CAMPUSES VALUES (38,'Ohio State University','University of the Pacific',2412);
INSERT INTO CAMPUSES VALUES (39,'Ohio State University','University of Wisconsin',503);
INSERT INTO CAMPUSES VALUES (40,'Saddleback College','Arizona State University',379);
INSERT INTO CAMPUSES VALUES (41,'Saddleback College','Massachusetts Institute of Technology (MIT)',2989);
INSERT INTO CAMPUSES VALUES (42,'Saddleback College','Northwestern',2033);
INSERT INTO CAMPUSES VALUES (43,'Saddleback College','Ohio State University',2252);
INSERT INTO CAMPUSES VALUES (44,'Saddleback College','University of  Michigan',2249);
INSERT INTO CAMPUSES VALUES (45,'Saddleback College','University of California, Irvine (UCI)',16);
INSERT INTO CAMPUSES VALUES (46,'Saddleback College','University of California, Los Angeles (UCLA)',66.3);
INSERT INTO CAMPUSES VALUES (47,'Saddleback College','University of Oregon',906);
INSERT INTO CAMPUSES VALUES (48,'Saddleback College','University of the Pacific',390);
INSERT INTO CAMPUSES VALUES (49,'Saddleback College','University of Wisconsin',1981);
INSERT INTO CAMPUSES VALUES (50,'University of  Michigan','Arizona State University',1956);
INSERT INTO CAMPUSES VALUES (51,'University of  Michigan','Massachusetts Institute of Technology (MIT)',803);
INSERT INTO CAMPUSES VALUES (52,'University of  Michigan','Northwestern',270);
INSERT INTO CAMPUSES VALUES (53,'University of  Michigan','Ohio State University',184);
INSERT INTO CAMPUSES VALUES (54,'University of  Michigan','Saddleback College',2249);
INSERT INTO CAMPUSES VALUES (55,'University of  Michigan','University of California, Irvine (UCI)',2245);
INSERT INTO CAMPUSES VALUES (56,'University of  Michigan','University of California, Los Angeles (UCLA)',2252);
INSERT INTO CAMPUSES VALUES (57,'University of  Michigan','University of Oregon',2347);
INSERT INTO CAMPUSES VALUES (58,'University of  Michigan','University of the Pacific',2318);
INSERT INTO CAMPUSES VALUES (59,'University of  Michigan','University of Wisconsin',391);
INSERT INTO CAMPUSES VALUES (60,'University of California, Irvine (UCI)','Arizona State University',375);
INSERT INTO CAMPUSES VALUES (61,'University of California, Irvine (UCI)','Massachusetts Institute of Technology (MIT)',2986);
INSERT INTO CAMPUSES VALUES (62,'University of California, Irvine (UCI)','Northwestern',2030);
INSERT INTO CAMPUSES VALUES (63,'University of California, Irvine (UCI)','Ohio State University',2248);
INSERT INTO CAMPUSES VALUES (64,'University of California, Irvine (UCI)','Saddleback College',16);
INSERT INTO CAMPUSES VALUES (65,'University of California, Irvine (UCI)','University of  Michigan',2245);
INSERT INTO CAMPUSES VALUES (66,'University of California, Irvine (UCI)','University of California, Los Angeles (UCLA)',51.5);
INSERT INTO CAMPUSES VALUES (67,'University of California, Irvine (UCI)','University of Oregon',899);
INSERT INTO CAMPUSES VALUES (68,'University of California, Irvine (UCI)','University of the Pacific',383);
INSERT INTO CAMPUSES VALUES (69,'University of California, Irvine (UCI)','University of Wisconsin',1978);
INSERT INTO CAMPUSES VALUES (70,'University of California, Los Angeles (UCLA)','Arizona State University',397);
INSERT INTO CAMPUSES VALUES (71,'University of California, Los Angeles (UCLA)','Massachusetts Institute of Technology (MIT)',2998);
INSERT INTO CAMPUSES VALUES (72,'University of California, Los Angeles (UCLA)','Northwestern',2043);
INSERT INTO CAMPUSES VALUES (73,'University of California, Los Angeles (UCLA)','Ohio State University',2261);
INSERT INTO CAMPUSES VALUES (74,'University of California, Los Angeles (UCLA)','Saddleback College',66.3);
INSERT INTO CAMPUSES VALUES (75,'University of California, Los Angeles (UCLA)','University of  Michigan',2252);
INSERT INTO CAMPUSES VALUES (76,'University of California, Los Angeles (UCLA)','University of California, Irvine (UCI)',51.5);
INSERT INTO CAMPUSES VALUES (77,'University of California, Los Angeles (UCLA)','University of Oregon',849);
INSERT INTO CAMPUSES VALUES (78,'University of California, Los Angeles (UCLA)','University of the Pacific',333);
INSERT INTO CAMPUSES VALUES (79,'University of California, Los Angeles (UCLA)','University of Wisconsin',1991);
INSERT INTO CAMPUSES VALUES (80,'University of Oregon','Arizona State University',1343);
INSERT INTO CAMPUSES VALUES (81,'University of Oregon','Massachusetts Institute of Technology (MIT)',3107);
INSERT INTO CAMPUSES VALUES (82,'University of Oregon','Northwestern',2151);
INSERT INTO CAMPUSES VALUES (83,'University of Oregon','Ohio State University',2241);
INSERT INTO CAMPUSES VALUES (84,'University of Oregon','Saddleback College',906);
INSERT INTO CAMPUSES VALUES (85,'University of Oregon','University of  Michigan',2347);
INSERT INTO CAMPUSES VALUES (86,'University of Oregon','University of California, Irvine (UCI)',899);
INSERT INTO CAMPUSES VALUES (87,'University of Oregon','University of California, Los Angeles (UCLA)',849);
INSERT INTO CAMPUSES VALUES (88,'University of Oregon','University of the Pacific',517);
INSERT INTO CAMPUSES VALUES (89,'University of Oregon','University of Wisconsin',2111);
INSERT INTO CAMPUSES VALUES (90,'University of the Pacific','Arizona State University',720);
INSERT INTO CAMPUSES VALUES (91,'University of the Pacific','Massachusetts Institute of Technology (MIT)',3057);
INSERT INTO CAMPUSES VALUES (92,'University of the Pacific','Northwestern',2102);
INSERT INTO CAMPUSES VALUES (93,'University of the Pacific','Ohio State University',2412);
INSERT INTO CAMPUSES VALUES (94,'University of the Pacific','Saddleback College',390);
INSERT INTO CAMPUSES VALUES (95,'University of the Pacific','University of  Michigan',2318);
INSERT INTO CAMPUSES VALUES (96,'University of the Pacific','University of California, Irvine (UCI)',383);
INSERT INTO CAMPUSES VALUES (97,'University of the Pacific','University of California, Los Angeles (UCLA)',333);
INSERT INTO CAMPUSES VALUES (98,'University of the Pacific','University of Oregon',517);
INSERT INTO CAMPUSES VALUES (99,'University of the Pacific','University of Wisconsin',2052);
INSERT INTO CAMPUSES VALUES (100,'University of Wisconsin','Arizona State University',1684);
INSERT INTO CAMPUSES VALUES (101,'University of Wisconsin','Massachusetts Institute of Technology (MIT)',1125);
INSERT INTO CAMPUSES VALUES (102,'University of Wisconsin','Northwestern',145);
INSERT INTO CAMPUSES VALUES (103,'University of Wisconsin','Ohio State University',503);
INSERT INTO CAMPUSES VALUES (104,'University of Wisconsin','Saddleback College',1981);
INSERT INTO CAMPUSES VALUES (105,'University of Wisconsin','University of  Michigan',391);
INSERT INTO CAMPUSES VALUES (106,'University of Wisconsin','University of California, Irvine (UCI)',1978);
INSERT INTO CAMPUSES VALUES (107,'University of Wisconsin','University of California, Los Angeles (UCLA)',1991);
INSERT INTO CAMPUSES VALUES (108,'University of Wisconsin','University of Oregon',2111);
INSERT INTO CAMPUSES VALUES (109,'University of Wisconsin','University of the Pacific',2052);
