INSERT INTO CAMPUSES VALUES (0,'Arizona State University','California State University, Fullerton',364);
INSERT INTO CAMPUSES VALUES (1,'Arizona State University','University of Texas',1007);
INSERT INTO CAMPUSES VALUES (2,'Massachusetts Institute of Technology (MIT)','California State University, Fullerton',2968);
INSERT INTO CAMPUSES VALUES (3,'Massachusetts Institute of Technology (MIT)','University of Texas',1959);
INSERT INTO CAMPUSES VALUES (4,'Northwestern','California State University, Fullerton',2013);
INSERT INTO CAMPUSES VALUES (5,'Northwestern','University of Texas',1311);
INSERT INTO CAMPUSES VALUES (6,'Ohio State University','California State University, Fullerton',2231);
INSERT INTO CAMPUSES VALUES (7,'Ohio State University','University of Texas',1235);
INSERT INTO CAMPUSES VALUES (8,'Saddleback College','California State University, Fullerton',29.3);
INSERT INTO CAMPUSES VALUES (9,'Saddleback College','University of Texas',1378);
INSERT INTO CAMPUSES VALUES (10,'University of California, Irvine (UCI)','California State University, Fullerton',20.2);
INSERT INTO CAMPUSES VALUES (11,'University of California, Irvine (UCI)','University of Texas',1375);
INSERT INTO CAMPUSES VALUES (12,'University of California, Los Angeles (UCLA)','California State University, Fullerton',47.9);
INSERT INTO CAMPUSES VALUES (13,'University of California, Los Angeles (UCLA)','University of Texas',1396);
INSERT INTO CAMPUSES VALUES (14,'University of  Michigan','California State University, Fullerton',2229);
INSERT INTO CAMPUSES VALUES (15,'University of  Michigan','University of Texas',1368);
INSERT INTO CAMPUSES VALUES (16,'University of Oregon','California State University, Fullerton',884);
INSERT INTO CAMPUSES VALUES (17,'University of Oregon','University of Texas',2073);
INSERT INTO CAMPUSES VALUES (18,'University of the Pacific','California State University, Fullerton',368);
INSERT INTO CAMPUSES VALUES (19,'University of the Pacific','University of Texas',1720);
INSERT INTO CAMPUSES VALUES (20,'University of Wisconsin','California State University, Fullerton',1963);
INSERT INTO CAMPUSES VALUES (21,'University of Wisconsin','University of Texas',1183);
INSERT INTO CAMPUSES VALUES (22,'California State University, Fullerton','Arizona State University',364);
INSERT INTO CAMPUSES VALUES (23,'California State University, Fullerton','Massachusetts Institute of Technology (MIT)',2968);
INSERT INTO CAMPUSES VALUES (24,'California State University, Fullerton','Northwestern',2013);
INSERT INTO CAMPUSES VALUES (25,'California State University, Fullerton','Ohio State University',2231);
INSERT INTO CAMPUSES VALUES (26,'California State University, Fullerton','Saddleback',29.3);
INSERT INTO CAMPUSES VALUES (27,'California State University, Fullerton','University of California, Irvine (UCI)',20.2);
INSERT INTO CAMPUSES VALUES (28,'California State University, Fullerton','University of California, Los Angeles (UCLA)',47.9);
INSERT INTO CAMPUSES VALUES (29,'California State University, Fullerton','University of  Michigan',2229);
INSERT INTO CAMPUSES VALUES (30,'California State University, Fullerton','University of Oregon',884);
INSERT INTO CAMPUSES VALUES (31,'California State University, Fullerton','University of the Pacific',368);
INSERT INTO CAMPUSES VALUES (32,'California State University, Fullerton','University of Texas',1758);
INSERT INTO CAMPUSES VALUES (33,'California State University, Fullerton','University of Wisconsin',1963);
INSERT INTO CAMPUSES VALUES (34,'University of Texas','Arizona State University',1007);
INSERT INTO CAMPUSES VALUES (35,'University of Texas','California State University, Fullerton',1758);
INSERT INTO CAMPUSES VALUES (36,'University of Texas','Massachusetts Institute of Technology (MIT)',1959);
INSERT INTO CAMPUSES VALUES (37,'University of Texas','Northwestern',1311);
INSERT INTO CAMPUSES VALUES (38,'University of Texas','Ohio State University',1235);
INSERT INTO CAMPUSES VALUES (39,'University of Texas','Saddleback',1378);
INSERT INTO CAMPUSES VALUES (40,'University of Texas','University of California, Irvine (UCI)',1375);
INSERT INTO CAMPUSES VALUES (41,'University of Texas','University of California, Los Angeles (UCLA)',1396);
INSERT INTO CAMPUSES VALUES (42,'University of Texas','University of  Michigan',1368);
INSERT INTO CAMPUSES VALUES (43,'University of Texas','University of Oregon',2073);
INSERT INTO CAMPUSES VALUES (44,'University of Texas','University of the Pacific',1720);
INSERT INTO CAMPUSES VALUES (45,'University of Texas','University of Wisconsin',1183);