INSERT INTO SOUVENIRS VALUES(0,'Arizona State University','Football Jersey',112.44);
INSERT INTO SOUVENIRS VALUES(1,'Arizona State University','Poster',9.43);
INSERT INTO SOUVENIRS VALUES(2,'Arizona State University','Sweatshirt',42.79);
INSERT INTO SOUVENIRS VALUES(3,'Arizona State University','Visor',9.44);
INSERT INTO SOUVENIRS VALUES(4,'California State University, Fullerton','Canopy',96.75);
INSERT INTO SOUVENIRS VALUES(5,'California State University, Fullerton','Flag',15.76);
INSERT INTO SOUVENIRS VALUES(6,'California State University, Fullerton','Keychain',7.98);
INSERT INTO SOUVENIRS VALUES(7,'Massachusetts Institute of Technology (MIT)','Key strap',5.66);
INSERT INTO SOUVENIRS VALUES(8,'Massachusetts Institute of Technology (MIT)','Tote Bag',13.49);
INSERT INTO SOUVENIRS VALUES(9,'Massachusetts Institute of Technology (MIT)','Tumbler',8.63);
INSERT INTO SOUVENIRS VALUES(10,'Northwestern','Bottle',7.65);
INSERT INTO SOUVENIRS VALUES(11,'Northwestern','Bracelet',64.99);
INSERT INTO SOUVENIRS VALUES(12,'Northwestern','Cup',8.76);
INSERT INTO SOUVENIRS VALUES(13,'Northwestern','Necklace',44.44);
INSERT INTO SOUVENIRS VALUES(14,'Ohio State University','Cooler',18.66);
INSERT INTO SOUVENIRS VALUES(15,'Ohio State University','Decal',7.63);
INSERT INTO SOUVENIRS VALUES(16,'Ohio State University','Football helmet',55.49);
INSERT INTO SOUVENIRS VALUES(17,'Saddleback College','Hat',15.76);
INSERT INTO SOUVENIRS VALUES(18,'Saddleback College','Sweatshirt',44.65);
INSERT INTO SOUVENIRS VALUES(19,'Saddleback College','T-shirt',23.21);
INSERT INTO SOUVENIRS VALUES(20,'University of  Michigan','Adjustable chair',26.92);
INSERT INTO SOUVENIRS VALUES(21,'University of  Michigan','Beach towel',19.74);
INSERT INTO SOUVENIRS VALUES(22,'University of  Michigan','Bucket hat',26.46);
INSERT INTO SOUVENIRS VALUES(23,'University of  Michigan','Shorts',33.44);
INSERT INTO SOUVENIRS VALUES(24,'University of California, Irvine (UCI)','Bobble head',12.12);
INSERT INTO SOUVENIRS VALUES(25,'University of California, Irvine (UCI)','Pants',48.88);
INSERT INTO SOUVENIRS VALUES(26,'University of California, Irvine (UCI)','Pennant',12.25);
INSERT INTO SOUVENIRS VALUES(27,'University of California, Irvine (UCI)','Polo shirt',55.79);
INSERT INTO SOUVENIRS VALUES(28,'University of California, Los Angeles (UCLA)','Football',54.45);
INSERT INTO SOUVENIRS VALUES(29,'University of California, Los Angeles (UCLA)','Blanket',22.79);
INSERT INTO SOUVENIRS VALUES(30,'University of California, Los Angeles (UCLA)','Jacket',74.98);
INSERT INTO SOUVENIRS VALUES(31,'University of California, Los Angeles (UCLA)','Pen and pencil set',11.45);
INSERT INTO SOUVENIRS VALUES(32,'University of Oregon','Auto emblem',6.96);
INSERT INTO SOUVENIRS VALUES(33,'University of Oregon','Key ring',6.94);
INSERT INTO SOUVENIRS VALUES(34,'University of Oregon','License plate cover',11.85);
INSERT INTO SOUVENIRS VALUES(35,'University of Texas','Coaster set',14.94);
INSERT INTO SOUVENIRS VALUES(36,'University of Texas','Face paint',7.53);
INSERT INTO SOUVENIRS VALUES(37,'University of Texas','Sports chair',85.99);
INSERT INTO SOUVENIRS VALUES(38,'University of the Pacific','Coaster set',12.73);
INSERT INTO SOUVENIRS VALUES(39,'University of the Pacific','Lawn chair',88.79);
INSERT INTO SOUVENIRS VALUES(40,'University of the Pacific','Reclining chair',165.44);
INSERT INTO SOUVENIRS VALUES(41,'University of the Pacific','Temporary tattoos',7.44);
INSERT INTO SOUVENIRS VALUES(42,'University of the Pacific','Water bottle',9.85);
INSERT INTO SOUVENIRS VALUES(43,'University of Wisconsin','Car magnet',8.76);
INSERT INTO SOUVENIRS VALUES(44,'University of Wisconsin','Cufflinks',56.87);
INSERT INTO SOUVENIRS VALUES(45,'University of Wisconsin','Ring',88.98);
INSERT INTO SOUVENIRS VALUES(46,'University of Wisconsin','Watch',104.99);
